version: '3.9'
services:
  app:
    container_name: 'mds-food-app-dev'
    image: mds-food-app-dev
    build:
      context: .
      dockerfile: .docker/dev.dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
